Added check for correctness of DAPTUP_MINIMAL_DAY_COUNT_TREATING_OUTDATED variable.
git-svn-id: https://daptup.svn.sourceforge.net/svnroot/daptup/trunk@58 645c1fc9-2b4d-0410-82a6-a7af763e6058

diff --git a/daptup b/daptup
--- a/daptup
+++ b/daptup
@@ -279,7 +279,14 @@ fi
 reset_color
 
 if [ "$DAPTUP_CHECK_FOR_OUTDATED_PACKAGES" == "y" ]; then
-	find_old_packages
+	# if DAPTUP_MINIMAL_DAY_COUNT_TREATING_OUTDATED variable contains non-numeric
+	# data, print an error and don't try to check for outdated packages
+	expr "$DAPTUP_MINIMAL_DAY_COUNT_TREATING_OUTDATED" + 0 >/dev/null 2>/dev/null
+	if [ "$?" == "0" ]; then
+		find_old_packages
+	else
+		echo "error: DAPTUP_MINIMAL_DAY_COUNT_TREATING_OUTDATED contains non-numeric data"
+	fi
 fi
 
 delete_temp_files
